### ISSUE TITLE
Build error on Crystal 0.17-3

### ISSUE THREAD

**Issue by puppetpies** [datanoise/amqp.cr#6]
I ran the gem_spec.sh and tried to build basic_get.cr from the examples directory.

[brian@orville examples]$ crystal basic_get.cr 
Error in ./basic_get.cr:2: while requiring "../src/amqp"

require "../src/amqp"
^

in /data2/Projects/amqp.cr/src/amqp.cr:1: while requiring "./amqp/*"

require "./amqp/*"
^

in /data2/Projects/amqp.cr/src/amqp/broker.cr:3: while requiring "./spec091"

require "./spec091"
^

Syntax error in /data2/Projects/amqp.cr/src/amqp/spec091.cr:1: unexpected token: in

Error in ./gen.cr:333: instantiating 'CodeGen:Module#generate(XML::Node, IO::FileDescriptor)'
      ^

**Comment by DougEverly** [comment]
Works ok with Crystal 0.17.4. Try that version.

**Comment by DougEverly** [comment]
Nevermind, I didn't run `gen_spec.sh`. When I did, I got the same errors.

**Comment by DougEverly** [comment]
PR #7 adds type annotations to gen.cr. Does not fully fix the problem, but reduces it to: 

```
Error in ./gen.cr:88: instance variable '@methods' of CodeGen::Class was not initialized in all of the 'initialize' methods, rendering it nilable

    @methods :  Array(CodeGen::Method)
```

which is odd, because I only see one initializer there. Maybe I am missing something?

**Comment by puppetpies** [comment]
Genspec now builds
